apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.appName }}
spec:
  provider:
    vault:
      server: "http://vault-internal.anilcloudengineer.online:8200"
      path: "roboshop-{{ .Values.env }}"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"